/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/maps/id/{id}": {
    get: {
      parameters: {
        path: {
          /** id */
          id: string;
        };
      };
      responses: {
        /** MapDetail */
        200: {
          schema: definitions["MapDetail"];
        };
        /** Not Found */
        404: unknown;
      };
    };
  };
  "/maps/ids/{ids}": {
    get: {
      parameters: {
        path: {
          /** Up to 50 ids seperated by commas */
          ids: string;
        };
      };
      responses: {
        /** MapDetail */
        200: {
          schema: definitions["MapDetail"];
        };
        /** Not Found */
        404: unknown;
      };
    };
  };
  "/maps/hash/{hash}": {
    get: {
      parameters: {
        path: {
          /** Up to 50 hashes seperated by commas */
          hash: string;
        };
      };
      responses: {
        /** MapDetail */
        200: {
          schema: definitions["MapDetail"];
        };
        /** Not Found */
        404: unknown;
      };
    };
  };
  "/maps/uploader/{id}/{page}": {
    get: {
      parameters: {
        path: {
          /** id */
          id: number;
          /** page */
          page?: number;
        };
      };
      responses: {
        /** SearchResponse */
        200: {
          schema: definitions["SearchResponse"];
        };
      };
    };
  };
  "/maps/collaborations/{id}": {
    get: {
      parameters: {
        query: {
          /** before */
          before?: string;
          /** 1 - 100 */
          pageSize?: number;
        };
        path: {
          /** id */
          id: number;
        };
      };
      responses: {
        /** SearchResponse */
        200: {
          schema: definitions["SearchResponse"];
        };
      };
    };
  };
  "/maps/latest": {
    get: {
      parameters: {
        query: {
          /**
           * Like `before` but will get you maps more recent than the time supplied.
           * YYYY-MM-DDTHH:MM:SS+00:00
           */
          after?: string;
          /** true = both, false = no ai */
          automapper?: boolean;
          /**
           * You probably want this. Supplying the uploaded time of the last map in the previous page will get you another page.
           * YYYY-MM-DDTHH:MM:SS+00:00
           */
          before?: string;
          /** 1 - 100 */
          pageSize?: number;
          /** sort */
          sort?:
            | "FIRST_PUBLISHED"
            | "UPDATED"
            | "LAST_PUBLISHED"
            | "CREATED"
            | "CURATED";
        };
      };
      responses: {
        /** SearchResponse */
        200: {
          schema: definitions["SearchResponse"];
        };
      };
    };
  };
  "/maps/deleted": {
    get: {
      parameters: {
        query: {
          /**
           * Like `before` but will get you maps deleted more recently than the time supplied.
           * YYYY-MM-DDTHH:MM:SS+00:00
           */
          after?: string;
          /**
           * You probably want this. Supplying the deleted time of the last map in the previous page will get you another page.
           * YYYY-MM-DDTHH:MM:SS+00:00
           */
          before?: string;
          /** 1 - 100 */
          pageSize?: number;
        };
      };
      responses: {
        /** DeletedResponse */
        200: {
          schema: definitions["DeletedResponse"];
        };
      };
    };
  };
  "/maps/plays/{page}": {
    get: {
      parameters: {
        path: {
          /** page */
          page?: number;
        };
      };
      responses: {
        /** SearchResponse */
        200: {
          schema: definitions["SearchResponse"];
        };
      };
    };
  };
  "/users/id/{id}": {
    get: {
      parameters: {
        path: {
          /** id */
          id: number;
        };
      };
      responses: {
        /** UserDetail */
        200: {
          schema: definitions["UserDetail"];
        };
        /** Not Found */
        404: unknown;
      };
    };
  };
  "/users/ids/{ids}": {
    get: {
      parameters: {
        path: {
          /** ids */
          ids: string;
        };
      };
      responses: {
        /** UserDetail */
        200: {
          schema: definitions["UserDetail"];
        };
        /** Not Found */
        404: unknown;
      };
    };
  };
  "/users/name/{name}": {
    get: {
      parameters: {
        path: {
          /** name */
          name: string;
        };
      };
      responses: {
        /** UserDetail */
        200: {
          schema: definitions["UserDetail"];
        };
        /** Not Found */
        404: unknown;
      };
    };
  };
  "/search/{page}": {
    get: {
      parameters: {
        query: {
          /** curator */
          curator?: boolean;
          /** firstUploadAfter */
          firstUploadAfter?: string;
          /** firstUploadBefore */
          firstUploadBefore?: string;
          /** lastUploadAfter */
          lastUploadAfter?: string;
          /** lastUploadBefore */
          lastUploadBefore?: string;
          /** maxDownvotes */
          maxDownvotes?: number;
          /** maxMaps */
          maxMaps?: number;
          /** maxRankedMaps */
          maxRankedMaps?: number;
          /** maxUpvotes */
          maxUpvotes?: number;
          /** minDownvotes */
          minDownvotes?: number;
          /** minMaps */
          minMaps?: number;
          /** minRankedMaps */
          minRankedMaps?: number;
          /** minUpvotes */
          minUpvotes?: number;
          /** order */
          order: "DESC" | "ASC";
          /** 1 - 100 */
          pageSize?: number;
          /** q */
          q?: string;
          /** sort */
          sort:
            | "RELEVANCE"
            | "BPM"
            | "DURATION"
            | "UPVOTES"
            | "DOWNVOTES"
            | "RATIO"
            | "MAPS"
            | "RANKED_MAPS"
            | "FIRST_UPLOAD"
            | "LAST_UPLOAD"
            | "MAP_AGE";
          /** verified */
          verified?: boolean;
        };
        path: {
          /** page */
          page?: number;
        };
      };
      responses: {
        /** UserSearchResponse */
        200: {
          schema: definitions["UserSearchResponse"];
        };
      };
    };
  };
  "/search/text/{page}": {
    get: {
      parameters: {
        query: {
          /**
           * Options are a little weird, I may add another enum field in future to make this clearer.
           * true = both, false = only ai, null = no ai
           */
          automapper?: boolean;
          /** Comma seperated list of characteristics */
          characteristics?: string;
          /** chroma */
          chroma?: boolean;
          /** cinema */
          cinema?: boolean;
          /** Comma seperated list of collaborators */
          collaborator?: string;
          /** curated */
          curated?: boolean;
          /** Comma seperated list of environments */
          environments?: string;
          /** followed */
          followed?: boolean;
          /** from */
          from?: string;
          /** fullSpread */
          fullSpread?: boolean;
          /** leaderboard */
          leaderboard: "All" | "Ranked" | "BeatLeader" | "ScoreSaber";
          /** Float */
          maxBlStars?: unknown;
          /** Float */
          maxBpm?: unknown;
          /** maxDownVotes */
          maxDownVotes?: number;
          /** maxDuration */
          maxDuration?: number;
          /** Float */
          maxNps?: unknown;
          /** Float */
          maxRating?: unknown;
          /** Float */
          maxSsStars?: unknown;
          /** maxUpVotes */
          maxUpVotes?: number;
          /** maxVotes */
          maxVotes?: number;
          /** me */
          me?: boolean;
          /** Float */
          minBlStars?: unknown;
          /** Float */
          minBpm?: unknown;
          /** minDownVotes */
          minDownVotes?: number;
          /** minDuration */
          minDuration?: number;
          /** Float */
          minNps?: unknown;
          /** Float */
          minRating?: unknown;
          /** Float */
          minSsStars?: unknown;
          /** minUpVotes */
          minUpVotes?: number;
          /** minVotes */
          minVotes?: number;
          /** noodle */
          noodle?: boolean;
          /** pageSize */
          pageSize?: number;
          /** q */
          q: string;
          /** sortOrder */
          sortOrder: "Latest" | "Relevance" | "Rating" | "Curated" | "Random";
          /** Tag query, separated by `,` (and) or `|` (or). Excluded tags are prefixed with `!`. */
          tags?: string;
          /** to */
          to?: string;
          /** verified */
          verified?: boolean;
        };
        path: {
          /** page */
          page?: number;
        };
      };
      responses: {
        /** SearchResponse */
        200: {
          schema: definitions["SearchResponse"];
        };
      };
    };
  };
  "/search/v1/{page}": {
    get: {
      parameters: {
        query: {
          /**
           * Options are a little weird, I may add another enum field in future to make this clearer.
           * true = both, false = only ai, null = no ai
           */
          automapper?: boolean;
          /** chroma */
          chroma?: boolean;
          /** cinema */
          cinema?: boolean;
          /** curated */
          curated?: boolean;
          /** followed */
          followed?: boolean;
          /** from */
          from?: string;
          /** fullSpread */
          fullSpread?: boolean;
          /** leaderboard */
          leaderboard: "All" | "Ranked" | "BeatLeader" | "ScoreSaber";
          /** Float */
          maxBpm?: unknown;
          /** maxDuration */
          maxDuration?: number;
          /** Float */
          maxNps?: unknown;
          /** Float */
          maxRating?: unknown;
          /** me */
          me?: boolean;
          /** Float */
          minBpm?: unknown;
          /** minDuration */
          minDuration?: number;
          /** Float */
          minNps?: unknown;
          /** Float */
          minRating?: unknown;
          /** noodle */
          noodle?: boolean;
          /** q */
          q: string;
          /** sortOrder */
          sortOrder: "Latest" | "Relevance" | "Rating" | "Curated" | "Random";
          /** Tag query, separated by `,` (and) or `|` (or). Excluded tags are prefixed with `!`. */
          tags?: string;
          /** to */
          to?: string;
          /** verified */
          verified?: boolean;
        };
        path: {
          /** page */
          page?: number;
        };
      };
      responses: {
        /** SearchResponse */
        200: {
          schema: definitions["SearchResponse"];
        };
      };
    };
  };
  "/users/verify": {
    post: {
      parameters: {
        body: {
          /** AuthRequest */
          noReflectionBody: definitions["AuthRequest"];
        };
      };
      responses: {
        /** ActionResponse */
        200: {
          schema: definitions["ActionResponse"];
        };
      };
    };
  };
  "/vote": {
    get: {
      parameters: {
        query: {
          /** since */
          since: string;
        };
      };
      responses: {
        /** ListOfVoteSummary */
        200: {
          schema: definitions["ListOfVoteSummary"];
        };
        /** Not Found */
        404: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** VoteRequest */
          noReflectionBody: definitions["VoteRequest"];
        };
      };
      responses: {
        /** ActionResponse */
        200: {
          schema: definitions["ActionResponse"];
        };
      };
    };
  };
  "/playlists/latest": {
    get: {
      parameters: {
        query: {
          /**
           * Like `before` but will get you maps more recent than the time supplied.
           * YYYY-MM-DDTHH:MM:SS+00:00
           */
          after?: string;
          /**
           * You probably want this. Supplying the uploaded time of the last map in the previous page will get you another page.
           * YYYY-MM-DDTHH:MM:SS+00:00
           */
          before?: string;
          /** 1 - 100 */
          pageSize?: number;
          /** sort */
          sort?: "UPDATED" | "SONGS_UPDATED" | "CREATED" | "CURATED";
        };
      };
      responses: {
        /** PlaylistSearchResponse */
        200: {
          schema: definitions["PlaylistSearchResponse"];
        };
      };
    };
  };
  "/playlists/search/{page}": {
    get: {
      parameters: {
        query: {
          /** curated */
          curated?: boolean;
          /** from */
          from?: string;
          /** includeEmpty */
          includeEmpty?: boolean;
          /** Float */
          maxNps?: unknown;
          /** Float */
          minNps?: unknown;
          /** q */
          q: string;
          /** sortOrder */
          sortOrder: "Latest" | "Relevance" | "Rating" | "Curated" | "Random";
          /** to */
          to?: string;
          /** verified */
          verified?: boolean;
        };
        path: {
          /** page */
          page?: number;
        };
      };
      responses: {
        /** PlaylistSearchResponse */
        200: {
          schema: definitions["PlaylistSearchResponse"];
        };
      };
    };
  };
  "/playlists/search/v1/{page}": {
    get: {
      parameters: {
        query: {
          /** curated */
          curated?: boolean;
          /** from */
          from?: string;
          /** includeEmpty */
          includeEmpty?: boolean;
          /** Float */
          maxNps?: unknown;
          /** Float */
          minNps?: unknown;
          /** q */
          q: string;
          /** sortOrder */
          sortOrder: "Latest" | "Relevance" | "Rating" | "Curated" | "Random";
          /** to */
          to?: string;
          /** verified */
          verified?: boolean;
        };
        path: {
          /** page */
          page?: number;
        };
      };
      responses: {
        /** PlaylistSearchResponse */
        200: {
          schema: definitions["PlaylistSearchResponse"];
        };
      };
    };
  };
  "/playlists/user/{userId}/{page}": {
    get: {
      parameters: {
        path: {
          /** page */
          page: number;
          /** userId */
          userId: number;
        };
      };
      responses: {
        /** PlaylistSearchResponse */
        200: {
          schema: definitions["PlaylistSearchResponse"];
        };
      };
    };
  };
  "/playlists/map/{mapId}/{page}": {
    get: {
      parameters: {
        query: {
          /** curated */
          curated?: boolean;
        };
        path: {
          /** mapId */
          mapId: string;
          /** page */
          page: number;
        };
      };
      responses: {
        /** PlaylistSearchResponse */
        200: {
          schema: definitions["PlaylistSearchResponse"];
        };
      };
    };
  };
  "/playlists/id/{id}/{page}": {
    get: {
      parameters: {
        path: {
          /** id */
          id: number;
          /** page */
          page?: number;
        };
      };
      responses: {
        /** PlaylistPage */
        200: {
          schema: definitions["PlaylistPage"];
        };
        /** Not Found */
        404: unknown;
      };
    };
  };
  "/playlists/id/{id}/batch": {
    post: {
      parameters: {
        body: {
          /** PlaylistBatchRequest */
          noReflectionBody: definitions["PlaylistBatchRequest"];
        };
        path: {
          /** id */
          id: number;
        };
      };
      responses: {
        /** ActionResponse */
        200: {
          schema: definitions["ActionResponse"];
        };
        /** ActionResponse */
        400: {
          schema: definitions["ActionResponse"];
        };
        /** ActionResponse */
        404: {
          schema: definitions["ActionResponse"];
        };
      };
    };
  };
}

export interface definitions {
  MapDetail: {
    automapper?: boolean;
    blQualified?: boolean;
    blRanked?: boolean;
    bookmarked?: boolean;
    collaborators?: definitions["UserDetail"][];
    /** Format: date-time */
    createdAt?: string;
    /** Format: date-time */
    curatedAt?: string;
    /** @description UserDetail */
    curator?: definitions["UserDetail"];
    /** @enum {string} */
    declaredAi?: "Admin" | "Uploader" | "SageScore" | "None";
    /** Format: date-time */
    deletedAt?: string;
    description?: string;
    id?: string;
    /** Format: date-time */
    lastPublishedAt?: string;
    /** @description MapDetailMetadata */
    metadata?: definitions["MapDetailMetadata"];
    name?: string;
    nsfw?: boolean;
    qualified?: boolean;
    ranked?: boolean;
    /** @description MapStats */
    stats?: definitions["MapStats"];
    tags?: (
      | "None"
      | "Tech"
      | "DanceStyle"
      | "Speed"
      | "Balanced"
      | "Challenge"
      | "Accuracy"
      | "Fitness"
      | "Swing"
      | "Nightcore"
      | "Folk"
      | "Family"
      | "Ambient"
      | "Funk"
      | "Jazz"
      | "Classical"
      | "Soul"
      | "Speedcore"
      | "Punk"
      | "RB"
      | "Holiday"
      | "Vocaloid"
      | "JRock"
      | "Trance"
      | "DrumBass"
      | "Comedy"
      | "Instrumental"
      | "Hardcore"
      | "KPop"
      | "Indie"
      | "Techno"
      | "House"
      | "Game"
      | "Film"
      | "Alt"
      | "Dubstep"
      | "Metal"
      | "Anime"
      | "HipHop"
      | "JPop"
      | "Dance"
      | "Rock"
      | "Pop"
      | "Electronic"
    )[];
    /** Format: date-time */
    updatedAt?: string;
    /** Format: date-time */
    uploaded?: string;
    /** @description UserDetail */
    uploader?: definitions["UserDetail"];
    versions?: definitions["MapVersion"][];
  };
  UserDetail: {
    admin?: boolean;
    avatar?: string;
    curator?: boolean;
    curatorTab?: boolean;
    description?: string;
    email?: string;
    /** @description UserFollowData */
    followData?: definitions["UserFollowData"];
    hash?: string;
    /** Format: int32 */
    id?: number;
    name?: string;
    /** @enum {string} */
    patreon?: "None" | "Supporter" | "SupporterPlus";
    playlistUrl?: string;
    seniorCurator?: boolean;
    /** @description UserStats */
    stats?: definitions["UserStats"];
    /** Format: date-time */
    suspendedAt?: string;
    testplay?: boolean;
    /** @enum {string} */
    type?: "DISCORD" | "SIMPLE" | "DUAL";
    uniqueSet?: boolean;
    /** Format: int32 */
    uploadLimit?: number;
    verifiedMapper?: boolean;
  };
  UserFollowData: {
    collab?: boolean;
    curation?: boolean;
    /** Format: int32 */
    followers?: number;
    following?: boolean;
    /** Format: int32 */
    follows?: number;
    upload?: boolean;
  };
  UserStats: {
    /** @description Float */
    avgBpm?: definitions["Float"];
    /** @description Float */
    avgDuration?: definitions["Float"];
    /** @description Float */
    avgScore?: definitions["Float"];
    /** @description UserDiffStats */
    diffStats?: definitions["UserDiffStats"];
    /** Format: date-time */
    firstUpload?: string;
    /** Format: date-time */
    lastUpload?: string;
    /** Format: int32 */
    rankedMaps?: number;
    /** Format: int32 */
    totalDownvotes?: number;
    /** Format: int32 */
    totalMaps?: number;
    /** Format: int32 */
    totalUpvotes?: number;
  };
  Float: { [key: string]: unknown };
  UserDiffStats: {
    /** Format: int32 */
    easy?: number;
    /** Format: int32 */
    expert?: number;
    /** Format: int32 */
    expertPlus?: number;
    /** Format: int32 */
    hard?: number;
    /** Format: int32 */
    normal?: number;
    /** Format: int32 */
    total?: number;
  };
  MapDetailMetadata: {
    /** @description Float */
    bpm?: definitions["Float"];
    /** Format: int32 */
    duration?: number;
    levelAuthorName?: string;
    songAuthorName?: string;
    songName?: string;
    songSubName?: string;
  };
  MapStats: {
    /** Format: int32 */
    downloads?: number;
    /** Format: int32 */
    downvotes?: number;
    /** Format: int32 */
    plays?: number;
    /** Format: int32 */
    reviews?: number;
    /** @description Float */
    score?: definitions["Float"];
    /** @description Float */
    scoreOneDP?: definitions["Float"];
    /** @enum {string} */
    sentiment?:
      | "PENDING"
      | "VERY_NEGATIVE"
      | "MOSTLY_NEGATIVE"
      | "MIXED"
      | "MOSTLY_POSITIVE"
      | "VERY_POSITIVE";
    /** Format: int32 */
    upvotes?: number;
  };
  MapVersion: {
    coverURL?: string;
    /** Format: date-time */
    createdAt?: string;
    diffs?: definitions["MapDifficulty"][];
    downloadURL?: string;
    feedback?: string;
    hash?: string;
    key?: string;
    previewURL?: string;
    /** @description Short */
    sageScore?: definitions["Short"];
    /** Format: date-time */
    scheduledAt?: string;
    /** @enum {string} */
    state?: "Uploaded" | "Testplay" | "Published" | "Feedback" | "Scheduled";
    /** Format: date-time */
    testplayAt?: string;
    testplays?: definitions["MapTestplay"][];
  };
  MapDifficulty: {
    /** @description Float */
    blStars?: definitions["Float"];
    /** Format: int32 */
    bombs?: number;
    /** @enum {string} */
    characteristic?:
      | "Standard"
      | "OneSaber"
      | "NoArrows"
      | "90Degree"
      | "360Degree"
      | "Lightshow"
      | "Lawless"
      | "Legacy";
    chroma?: boolean;
    cinema?: boolean;
    /** @enum {string} */
    difficulty?: "Easy" | "Normal" | "Hard" | "Expert" | "ExpertPlus";
    /** @enum {string} */
    environment?:
      | "DefaultEnvironment"
      | "TriangleEnvironment"
      | "NiceEnvironment"
      | "BigMirrorEnvironment"
      | "KDAEnvironment"
      | "MonstercatEnvironment"
      | "CrabRaveEnvironment"
      | "DragonsEnvironment"
      | "OriginsEnvironment"
      | "PanicEnvironment"
      | "RocketEnvironment"
      | "GreenDayEnvironment"
      | "GreenDayGrenadeEnvironment"
      | "TimbalandEnvironment"
      | "FitBeatEnvironment"
      | "LinkinParkEnvironment"
      | "BTSEnvironment"
      | "KaleidoscopeEnvironment"
      | "InterscopeEnvironment"
      | "SkrillexEnvironment"
      | "BillieEnvironment"
      | "HalloweenEnvironment"
      | "GagaEnvironment"
      | "GlassDesertEnvironment"
      | "MultiplayerEnvironment"
      | "WeaveEnvironment"
      | "PyroEnvironment"
      | "EDMEnvironment"
      | "TheSecondEnvironment"
      | "LizzoEnvironment"
      | "TheWeekndEnvironment"
      | "RockMixtapeEnvironment"
      | "Dragons2Environment"
      | "Panic2Environment"
      | "QueenEnvironment"
      | "LinkinPark2Environment"
      | "TheRollingStonesEnvironment"
      | "LatticeEnvironment"
      | "DaftPunkEnvironment"
      | "HipHopEnvironment"
      | "ColliderEnvironment"
      | "BritneyEnvironment"
      | "Monstercat2Environment"
      | "MetallicaEnvironment";
    /** Format: int32 */
    events?: number;
    label?: string;
    /** Format: double */
    length?: number;
    /** Format: int32 */
    maxScore?: number;
    me?: boolean;
    ne?: boolean;
    /** @description Float */
    njs?: definitions["Float"];
    /** Format: int32 */
    notes?: number;
    /** Format: double */
    nps?: number;
    /** Format: int32 */
    obstacles?: number;
    /** @description Float */
    offset?: definitions["Float"];
    /** @description MapParitySummary */
    paritySummary?: definitions["MapParitySummary"];
    /** Format: double */
    seconds?: number;
    /** @description Float */
    stars?: definitions["Float"];
  };
  MapParitySummary: {
    /** Format: int32 */
    errors?: number;
    /** Format: int32 */
    resets?: number;
    /** Format: int32 */
    warns?: number;
  };
  Short: { [key: string]: unknown };
  MapTestplay: {
    /** Format: date-time */
    createdAt?: string;
    feedback?: string;
    /** Format: date-time */
    feedbackAt?: string;
    /** @description UserDetail */
    user?: definitions["UserDetail"];
    video?: string;
  };
  SearchResponse: {
    docs?: definitions["MapDetail"][];
    /** @description SearchInfo */
    info?: definitions["SearchInfo"];
    redirect?: string;
  };
  SearchInfo: {
    /** @description Float */
    duration?: definitions["Float"];
    /** Format: int32 */
    pages?: number;
    /** Format: int32 */
    total?: number;
  };
  DeletedResponse: {
    docs?: definitions["DeletedMap"][];
  };
  DeletedMap: {
    /** Format: date-time */
    deletedAt?: string;
    id?: string;
  };
  UserSearchResponse: {
    docs?: definitions["UserDetail"][];
    /** @description SearchInfo */
    info?: definitions["SearchInfo"];
  };
  AuthRequest: {
    oculusId?: string;
    proof?: string;
    steamId?: string;
  };
  ActionResponse: {
    errors?: string[];
    success?: boolean;
  };
  ListOfVoteSummary: definitions["VoteSummary"][];
  VoteSummary: {
    /** Format: int32 */
    downvotes?: number;
    hash?: string;
    key64?: string;
    /** Format: int32 */
    mapId?: number;
    /** Format: double */
    score?: number;
    /** Format: int32 */
    upvotes?: number;
  };
  VoteRequest: {
    /** @description AuthRequest */
    auth?: definitions["AuthRequest"];
    direction?: boolean;
    hash?: string;
  };
  PlaylistSearchResponse: {
    docs?: definitions["PlaylistFull"][];
    /** @description SearchInfo */
    info?: definitions["SearchInfo"];
  };
  PlaylistFull: {
    /** @description IPlaylistConfig */
    config?: definitions["IPlaylistConfig"];
    /** Format: date-time */
    createdAt?: string;
    /** Format: date-time */
    curatedAt?: string;
    /** @description UserDetail */
    curator?: definitions["UserDetail"];
    /** Format: date-time */
    deletedAt?: string;
    description?: string;
    downloadURL?: string;
    name?: string;
    /** @description UserDetail */
    owner?: definitions["UserDetail"];
    /** Format: int32 */
    playlistId?: number;
    playlistImage?: string;
    playlistImage512?: string;
    /** Format: date-time */
    songsChangedAt?: string;
    /** @description PlaylistStats */
    stats?: definitions["PlaylistStats"];
    /** @enum {string} */
    type?: "Private" | "Public" | "System" | "Search";
    /** Format: date-time */
    updatedAt?: string;
  };
  IPlaylistConfig: { [key: string]: unknown };
  PlaylistStats: {
    /** @description Float */
    avgScore?: definitions["Float"];
    /** Format: int32 */
    downVotes?: number;
    /** Format: int64 */
    mapperCount?: number;
    /** Format: double */
    maxNps?: number;
    /** Format: double */
    maxNpsTwoDP?: number;
    /** Format: double */
    minNps?: number;
    /** Format: double */
    minNpsTwoDP?: number;
    /** @description Float */
    scoreOneDP?: definitions["Float"];
    /** Format: int32 */
    totalDuration?: number;
    /** Format: int32 */
    totalMaps?: number;
    /** Format: int32 */
    upVotes?: number;
  };
  PlaylistPage: {
    maps?: definitions["MapDetailWithOrder"][];
    /** @description PlaylistFull */
    playlist?: definitions["PlaylistFull"];
  };
  MapDetailWithOrder: {
    /** @description MapDetail */
    map?: definitions["MapDetail"];
    /** @description Float */
    order?: definitions["Float"];
  };
  PlaylistBatchRequest: {
    hashes?: string[];
    ignoreUnknown?: boolean;
    inPlaylist?: boolean;
    keys?: string[];
  };
}

export interface operations {}

export interface external {}
